version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/geospatial:latest
        environment:
          NOT_CRAN: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
            - deps1-{{ .Branch }}
            - deps1-
      - run:
          command: |
            R -e "devtools::install_deps(dependencies = TRUE)"
            R -e "devtools::install_github('MangoTheCat/goodpractice')"
          no_output_timeout: 30m
      - run:
          command: |
            R -e "devtools::check(run_dont_test = TRUE)"
          no_output_timeout: 30m
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          command: |
            mkdir /root/main/artifacts
            R -e "devtools::install()"
            R -e "goodpractice::gp(checks = grep('(rcmdcheck|covr)', goodpractice::all_checks(), invert=TRUE, value=TRUE))"
            R -e "cv <- covr::package_coverage(); print(cv); covr::report(x = cv, file = '/root/main/artifacts/gsodr-coverage.html', browse=FALSE)"
            R CMD Rd2pdf --force --output='/root/main/artifacts/gsodr-manual.pdf' .
          no_output_timeout: 30m
      - store_artifacts:
          path: /root/main/artifacts/
          destination: artifacts
